# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Simon Bäder
title: Techie
email: sb@sb.com
website: https://simonbaeder.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: simonbaeder
github_username:  simonbaeder
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: simonbaeder
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hallo, ich bin Simon. Wirtschaftsinformatiker mit Erfahrung in Leadership, Projektmanagement, E-Business, Prozess-Optimierung, uvm. Im Moment interessiere ich mich für die Themen Streaming, Agilität, Elektromobilität, Blockchain, Digitalisierung und Netzpolitik. In meiner Freizeit bin ich Papa, Bitcoin-Purist, Tesla- und LEGO-Fanboy ;)

content:

  - title: Erfahrung # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ZHAW
        link: zhaw.ch
        # link_text: ZHAW
        sub_title: Teamleiter ICT Standortsupport Winterthur
        caption: Juli 2019 - heute
        quote: >
          Personelle und fachliche Verantwortung für 15 Mitarbeitende an 5 Standorten in Winterthur
        description: | # this will include new lines to allow paragraphs
            Neu-Positionierung des ICT Support als Shared Service innerhalb der agilen ICT (nach SAFe)
            Einführung von KPI im ICT Support
            Begleitung diverser Bauprojekte als ICT Baukoordinator
            Koordination der Aktivitäten im Bereich Webex als UC-Lösung

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ZHAW
        caption: 2020
        sub_title: CAS IT-Leadership und innovative Organisationen
        quote: >
          Der CAS «IT-Leadership und innovative Organisationen» vermittelt einen fundierten Einblick in personen- und teambezogene Handlungs- und Gestaltungsmöglichkeiten.
        description: | # this will include new lines to allow paragraphs
          [Weitere Informationen zum CAS](https://www.zhaw.ch/de/sml/weiterbildung/detail/kurs/cas-it-leadership-und-innovative-organisationen/)

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Bitcoin
      - Tesla

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag